version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    base-directory: ./BlueBank/BlueBank/
    commands:
      - echo "Build started"
      - mvn clean install -DskipTests
  post_build:
    base-directory: ./BlueBank/BlueBank/
    commands:
      - echo "Pipeline success"
      - mvn package
artifacts:
  files:
    - BlueBank.jar
  base-directory: ./BlueBank/


   
