version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo "Build started"
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo "Pipeline success"
      - mv target/*.jar BlueBank.jar
artifacts:
  files:
    - BlueBank.jar
    - appspec.yml
  discard-paths: yes
