version: '3'
services:
  docker-mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  docker-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: bluebank_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_HOSTNAME=docker-mysql
      - DB_PORT=3306
      - DB_DATABASE=blueBank
      - DB_PASS=root
    depends_on:
      - docker-mysql
 
 
